services:
  medisync-web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SUPABASE_URL: ${SUPABASE_URL}
        SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
        DEEPSEEK_BASE_URL: ${DEEPSEEK_BASE_URL}
        DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
        HUGGINGFACE_BASE_URL: ${HUGGINGFACE_BASE_URL}
        HUGGINGFACE_API_KEY: ${HUGGINGFACE_API_KEY}
        HUGGINGFACE_DEFAULT_MODEL: ${HUGGINGFACE_DEFAULT_MODEL}
    ports:
      - "8080:80"
