name: medisynch
description: "My Patients - Modern medical app UI (Phase 1: UI only)."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # Localization (Arabic/English etc.)
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # UI / Routing / State (UI phase)
  go_router: ^17.0.1
  flutter_riverpod: ^3.1.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  intl: ^0.20.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.2
  pdf: ^3.11.3
  printing: ^5.14.2
  file_picker: ^10.3.8
  lucide_icons: ^0.257.0
  flutter_image_compress: ^2.4.0
  flutter_animate: ^4.5.2
  sizer: ^3.1.3
  font_awesome_flutter: ^10.12.0
  path_provider: ^2.1.5
  connectivity_plus: ^7.0.0
  share_plus: ^12.0.1
  win32: ^5.15.0
  infinite_scroll_pagination: ^5.1.1
  sensors_plus: ^7.0.0
  url_launcher: ^6.3.2
  device_info_plus: ^12.3.0
  flutter_local_notifications: ^19.5.0
  built_value: ^8.12.1
  uuid: ^4.5.2
  http: ^1.6.0
  crypto: ^3.0.7
  image_picker: ^1.2.1
  flutter_secure_storage: ^10.0.0
  shimmer: ^3.0.0
  logging: ^1.3.0
  local_auth: ^3.0.0
  in_app_review: ^2.0.11
  mobile_scanner: ^7.1.4
  pinput: ^6.0.1
  upgrader: ^12.3.0
  path: ^1.9.1
  supabase_flutter: ^2.12.0
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  flutter_launcher_icons: ^0.14.2

flutter_launcher_icons:
  image_path: assets/icon/medisync.png
  android: true
  ios: true
  web:
    generate: true
    image_path: assets/icon/medisync.png
  windows:
    generate: true
    image_path: assets/icon/medisync.png
  macos:
    generate: true
    image_path: assets/icon/medisync.png

flutter:
  uses-material-design: true


  # Assets
  assets:
    - assets/icon/

